# Edikted Shipments — Data Profile

Per-finding evidence sections first, consolidated summary at the end.

| # | Section | Content |
|---|---------|---------|
| 1 | **Setup** | Imports, DB connection, load all 6 raw tables, define `is_str_null` helper and Pandera schemas |
| 2 | **EDA** | Null rates per column, numeric ranges, categorical distributions, date spans, source file breakdown |
| 3 | **Finding #1** | Column drift — 6 corrupted rows, Pandera multi-column failure map, drift % per source |
| 4 | **Finding #2** | `join_order_id` / `join_order_name` wrong for 100% of rows |
| 5 | **Finding #3** | Dirty column names in `edikted_1sa112` — 3 artifact duplicates |
| 6 | **Finding #4** | Column name variants between JSON and CSV sources |
| 7 | **Finding #5** | String null representations: `'None'`, `'NaN'`, `''`, `'N/A'`, `'----'` mixed throughout |
| 8 | **Finding #6** | `ID` absent in JSON sources |
| 9 | **Finding #7** | Zero `total_charge` rows — 11 valid free shipments |
| 10 | **Finding #8** | Same `order_id` across multiple source files — confirmed distinct shipments |
| 11 | **Findings #9–10** | Synthetic data caps: `total_charge` ≤ $100, `weight_lbs` ≤ 20, non-real tracking format |
| 12 | **Summary** | Ranked findings table — severity, problem, dbt fix location, rationale, status |

---
## 1 — Setup

All 6 raw tables loaded as-is from Postgres `raw.*`. Every column is `text` —
the ingest layer preserves source strings exactly to avoid silent type-coercion loss.
Pandera check helpers and schemas defined here once, referenced by each finding section below.

In [118]:
import os
import pandas as pd
import pandera as pa
from pandera import Column, Check, DataFrameSchema
from IPython.display import display
import sqlalchemy

POSTGRES_CONN = os.environ.get('POSTGRES_CONN', 'postgresql://postgres:postgres@localhost:5432/warehouse')
engine = sqlalchemy.create_engine(POSTGRES_CONN)

TABLES      = ['edikted_112412','edikted_212412','edikted_212423','background_image','edikted_1sa112','edikted_1sa122']
CSV_TABLES  = ['edikted_112412','edikted_212412','edikted_212423','background_image']
JSON_TABLES = ['edikted_1sa112','edikted_1sa122']

# Known null sentinels — found in raw data across all sources.
# Includes quoted variants ('"None"') and concatenated accidents ('NoneNone') found in `customs`.
STRING_NULLS = ['None','NaN','','null','NULL','nan','none','N/A','n/a','NA','#N/A','"None"','NoneNone']

def is_str_null(s):
    """True where value is any known null sentinel, dash-only string (e.g. '----'),
    or quoted null variant (e.g. '"None"')."""
    return s.isin(STRING_NULLS) | s.isna() | s.str.match(r'^-+$', na=False)

print('Pandera:', pa.__version__)

Pandera: 0.32.0

In [119]:
raw = {}
with engine.connect() as conn:
    for tbl in TABLES:
        raw[tbl] = pd.read_sql(f'SELECT * FROM raw."{tbl}"', conn)

overview = pd.DataFrame([
    {'table': t, 'rows': f'{len(df):,}', 'cols': len(df.columns),
     'source_type': 'CSV' if t in CSV_TABLES else 'JSON'}
    for t, df in raw.items()
])
display(overview)
print(f'Total rows: {sum(len(df) for df in raw.values()):,}')

              table    rows  cols source_type
0    edikted_112412  50,000    92         CSV
1    edikted_212412  40,000    92         CSV
2    edikted_212423  34,000    92         CSV
3  background_image  30,000    92         CSV
4    edikted_1sa112  40,000    97        JSON
5    edikted_1sa122  30,000    91        JSON

Total rows: 224,000

In [120]:
# Pandera check helpers + dynamic schema builder — covers ALL columns

def numeric_or_null(s):
    return s.str.match(r'^-?[0-9]+(\.[0-9]+)?$', na=False) | is_str_null(s)

def date_or_null(s):
    return pd.to_datetime(s.where(~is_str_null(s), other=pd.NaT), errors='coerce').notna() | is_str_null(s)

def no_numeric_leak(s):
    return ~s.str.match(r'^-?[0-9]+(\.[0-9]+)?$', na=False)

def valid_id(s):
    return s.str.match(r'^[0-9]+$', na=False)

def no_drift(s):
    return s != ''

# Column classification by name pattern
DATE_KW    = ('date', 'datetime', 'time')
NUMERIC_KW = ('charge', 'fee', 'fees', 'invoice', 'amount', 'credit',
              'lbs', 'weight', 'surcharge', 'subsidies', 'duties',
              'tax', 'duty', 'pst', 'hst', 'fuel', 'das', 'peak',
              'dimensional', 'customs', 'declared_value', 'zone', 'count_')
CATEG_COLS = {'carrier', 'service'}
LAST_COL   = 'additional_handling_length_girth'

def classify(col):
    c = col.lower()
    if c == LAST_COL:                      return 'drift'
    if c in CATEG_COLS:                    return 'categorical'
    if any(k in c for k in DATE_KW):       return 'date'
    if any(k in c for k in NUMERIC_KW):    return 'numeric'
    return 'text'

def build_schema(df, is_csv=True):
    cols = {}
    for col in df.columns:
        kind = classify(col)
        if col == 'ID' and is_csv:
            cols[col] = Column(str, Check(valid_id, element_wise=False, error='Malformed ID'), nullable=False)
        elif kind == 'drift':
            cols[col] = Column(str, Check(no_drift, element_wise=False, error='Blank last col — column drift'), nullable=True)
        elif kind == 'date':
            cols[col] = Column(str, Check(date_or_null, element_wise=False, error=f'Unparseable {col}'), nullable=True)
        elif kind == 'numeric':
            cols[col] = Column(str, Check(numeric_or_null, element_wise=False, error=f'Non-numeric {col}'), nullable=True)
        elif kind == 'categorical':
            cols[col] = Column(str, Check(no_numeric_leak, element_wise=False, error=f'Numeric in {col} — drift'), nullable=True)
        else:
            # text: register in schema to satisfy strict=True — no value constraint
            cols[col] = Column(str, nullable=True)
    return DataFrameSchema(columns=cols, strict=True, coerce=False)

schema_map = {tbl: build_schema(raw[tbl], is_csv=(tbl in CSV_TABLES)) for tbl in TABLES}

# Coverage summary
print('Schema coverage:')
for tbl, schema in schema_map.items():
    kinds = {}
    for col in raw[tbl].columns:
        k = 'id' if (col == 'ID' and tbl in CSV_TABLES) else classify(col)
        kinds[k] = kinds.get(k, 0) + 1
    checked = len(schema.columns)
    total   = len(raw[tbl].columns)
    print(f'  {tbl}: {checked}/{total} cols with checks — {kinds}')

Schema coverage:
  edikted_112412: 92/92 cols with checks — {'id': 1, 'text': 49, 'date': 6, 'numeric': 33, 'categorical': 2, 'drift': 1}
  edikted_212412: 92/92 cols with checks — {'id': 1, 'text': 49, 'date': 6, 'numeric': 33, 'categorical': 2, 'drift': 1}
  edikted_212423: 92/92 cols with checks — {'id': 1, 'text': 49, 'date': 6, 'numeric': 33, 'categorical': 2, 'drift': 1}
  background_image: 92/92 cols with checks — {'id': 1, 'text': 49, 'date': 6, 'numeric': 33, 'categorical': 2, 'drift': 1}
  edikted_1sa112: 97/97 cols with checks — {'text': 49, 'date': 7, 'numeric': 38, 'categorical': 2, 'drift': 1}
  edikted_1sa122: 91/91 cols with checks — {'text': 49, 'date': 6, 'numeric': 33, 'categorical': 2, 'drift': 1}

---
## 2 — EDA

Exploratory snapshot of all 6 raw sources **before** any cleaning or fixing.
Covers: null rates per column, numeric ranges, categorical distributions, date spans, source file breakdown.

| Cell | Content |
|------|---------|
| Null rates | % null per canonical column (effective null = `'None'`, `'NaN'`, `''`, SQL NULL) |
| Numeric ranges | min / mean / p50 / p95 / max for all 33 numeric columns |
| Categoricals | unique values + share for carrier, service, order_type, etc. |
| Date spans | min / max / span for all 6 date columns |
| Source files | rows per `source_file` value per raw table |

In [121]:
# Null rates per column across all sources combined
# Effective null = 'None', 'NaN', '', 'N/A', 'n/a', '----' (any dash-only string), SQL NULL
import numpy as np

canon_cols     = list(raw['edikted_112412'].columns)
combined       = pd.concat(list(raw.values()), ignore_index=True)
combined_canon = combined[[c for c in canon_cols if c in combined.columns]]

null_rates = pd.DataFrame({
    'column': combined_canon.columns,
    'type':   [classify(c) for c in combined_canon.columns],
    'null_%': [round(100 * is_str_null(combined_canon[c]).sum() / len(combined_canon), 1)
               for c in combined_canon.columns],
}).sort_values('null_%', ascending=False).reset_index(drop=True)

print(f'Total rows (all sources combined): {len(combined_canon):,}  |  Columns (canonical): {len(combined_canon.columns)}')
print(f'Columns with >50% null:  {(null_rates["null_%"] > 50).sum()}')
print(f'Columns with 0% null:    {(null_rates["null_%"] == 0).sum()}')
display(null_rates)

Total rows (all sources combined): 224,000  |  Columns (canonical): 92
Columns with >50% null:  46
Columns with 0% null:    39

                   column     type  null_%
0                    zone  numeric   100.0
1             dimensional  numeric   100.0
2                received     text   100.0
3    addl_handling_weight  numeric   100.0
4      receiver_address_1     text   100.0
..                    ...      ...     ...
87          receiver_name     text     0.0
88       receiver_country     text     0.0
89  receiver_company_name     text     0.0
90     shopify_order_date     date     0.0
91           _source_file     text     0.0

[92 rows x 3 columns]

In [122]:
# Numeric column stats — min / mean / p50 / p95 / max across all sources
numeric_cols = [c for c in canon_cols if classify(c) == 'numeric' and c in combined.columns]

stats_rows = []
for col in numeric_cols:
    clean = combined[col].where(~is_str_null(combined[col]), other=np.nan)
    vals  = pd.to_numeric(clean, errors='coerce').dropna()
    if len(vals) == 0:
        continue
    stats_rows.append({
        'column':   col,
        'non_null': f'{len(vals):,}',
        'null_%':   f'{round(100 * (1 - len(vals) / len(combined)), 1)}%',
        'min':      round(vals.min(), 2),
        'mean':     round(vals.mean(), 2),
        'p50':      round(vals.median(), 2),
        'p95':      round(vals.quantile(0.95), 2),
        'max':      round(vals.max(), 2),
    })

display(pd.DataFrame(stats_rows))

,column,non_null,null_%,min,mean,p50,p95,max
0,warehouse_invoice,"217,091",3.1%,3.980329e+08,7.023497e+10,1.000100e+11,1.000100e+11,1.000100e+11
1,carriers_fees,"223,999",0.0%,0.000000e+00,5.002000e+01,5.004000e+01,9.502000e+01,1.000000e+02
2,invoice_num,"212,716",5.0%,1.000100e+11,1.000100e+11,1.000100e+11,1.000100e+11,1.000100e+11
3,invoice_number,"212,861",5.0%,1.000100e+11,1.000100e+11,1.000100e+11,1.000100e+11,1.000100e+11
4,total_charge,"223,997",0.0%,0.000000e+00,4.999000e+01,4.998000e+01,9.501000e+01,1.000000e+02
5,weight_billable,"223,997",0.0%,0.000000e+00,5.009000e+01,5.008000e+01,9.505000e+01,1.000000e+02
6,zone,3,100.0%,1.353790e+05,2.617203e+05,1.964890e+05,4.276126e+05,4.532930e+05
7,count_parcels,"223,997",0.0%,1.000000e+00,5.510000e+00,6.000000e+00,1.000000e+01,1.000000e+01
8,duties_paid_by_customer,3,100.0%,1.470000e+00,3.320000e+00,3.480000e+00,4.870000e+00,5.020000e+00
9,weight_lbs,"223,997",0.0%,0.000000e+00,1.000000e+01,1.001000e+01,1.900000e+01,2.000000e+01

In [123]:
# Categorical column unique values and distributions
categ_cols_to_check = [
    'carrier', 'service', 'order_type', 'transportation_type',
    'shopify_order_type', 'otype', 'is_replacement_order',
]

for col in categ_cols_to_check:
    if col not in combined.columns:
        continue
    clean = combined[col].where(~is_str_null(combined[col]), other=pd.NA).dropna()
    vc    = clean.value_counts().reset_index()
    vc.columns = [col, 'count']
    vc['%'] = (100 * vc['count'] / len(clean)).round(1).astype(str) + '%'
    print(f'\n{col} — {len(vc)} unique value(s), {len(clean):,} non-null:')
    display(vc.head(20))

carrier — 5 unique value(s), 224,000 non-null:

  carrier  count      %
0   Fedex  56226  25.1%
1    USPS  56033  25.0%
2     UPS  55920  25.0%
3     DHL  55820  24.9%
4   42.44      1   0.0%

service — 6 unique value(s), 224,000 non-null:

   service  count      %
0   ground  74797  33.4%
1      air  74636  33.3%
2  express  74564  33.3%
3    39.36      1   0.0%
4    50.85      1   0.0%
5    35.52      1   0.0%

order_type — 5 unique value(s), 224,000 non-null:

  order_type  count      %
0     return  56198  25.1%
1   dropship  56189  25.1%
2   exchange  55890  25.0%
3  undefined  55722  24.9%
4     228271      1   0.0%

transportation_type — 6 unique value(s), 224,000 non-null:

                                 transportation_type  count      %
0                                          container  74786  33.4%
1                                             parcel  74624  33.3%
2                                             pallet  74587  33.3%
3  04272 Brian Points Apt. 139\nPort Brittanystad...      1   0.0%
4        6944 Vincent Corners\nNatalieport, WI 70222      1   0.0%
5  5619 Donald Lane Suite 648\nHamiltonberg, CT 4...      1   0.0%

shopify_order_type — 4 unique value(s), 223,994 non-null:

  shopify_order_type  count      %
0          undefined  56111  25.1%
1           exchange  56096  25.0%
2           dropship  56045  25.0%
3             return  55742  24.9%

otype — 10 unique value(s), 224,000 non-null:

       otype  count      %
0     return  56189  25.1%
1   exchange  56030  25.0%
2   dropship  56027  25.0%
3  undefined  55748  24.9%
4    5p95573      1   0.0%
5    j467594      1   0.0%
6    i763871      1   0.0%
7    942249F      1   0.0%
8    894065M      1   0.0%
9    423q400      1   0.0%

is_replacement_order — 4 unique value(s), 221,750 non-null:

  is_replacement_order   count      %
0                False  176918  79.8%
1                 True   44829  20.2%
2                    1       2   0.0%
3                   10       1   0.0%

In [124]:
# Date column min / max spans across all sources
date_cols = [c for c in canon_cols if classify(c) == 'date' and c in combined.columns]

rows = []
for col in date_cols:
    clean  = combined[col].where(~is_str_null(combined[col]), other=np.nan)
    parsed = pd.to_datetime(clean, errors='coerce').dropna()
    rows.append({
        'column':    col,
        'non_null':  f'{len(parsed):,}',
        'null_%':    f'{round(100 * (1 - len(parsed) / len(combined)), 1)}%',
        'min':       str(parsed.min().date()) if len(parsed) else '—',
        'max':       str(parsed.max().date()) if len(parsed) else '—',
        'span_days': (parsed.max() - parsed.min()).days if len(parsed) else 0,
    })

display(pd.DataFrame(rows).sort_values('min').reset_index(drop=True))

                 column non_null null_%         min         max  span_days
0       insert_datetime  223,998   0.0%  2023-06-10  2023-09-07         89
1                  date  223,999   0.0%  2023-06-10  2023-09-07         89
2          invoice_date  223,999   0.0%  2023-06-10  2023-09-07         89
3  date_received_in_hub  223,997   0.0%  2023-06-10  2023-09-07         89
4    shopify_order_date  223,994   0.0%  2023-06-10  2023-09-07         89
5            order_date  223,994   0.0%  2023-06-10  2023-09-07         89

In [125]:
# Source file breakdown — rows per source_file per raw table, combined into one table
rows = []
for tbl, df in raw.items():
    if 'source_file' not in df.columns:
        continue
    vc = (df['source_file']
          .replace(STRING_NULLS, pd.NA)
          .dropna()
          .value_counts()
          .reset_index()
          .rename(columns={'source_file': 'file', 'count': 'rows'}))
    vc.insert(0, 'table', tbl)
    rows.append(vc)

df_sources = pd.concat(rows, ignore_index=True)
print(f'Total unique source files across all tables: {df_sources["file"].nunique():,}')
print(f'Total rows represented: {df_sources["rows"].sum():,}')
display(df_sources)

Total unique source files across all tables: 217
Total rows represented: 224,000

               table                                               file  rows
0     edikted_112412  /share/transportation/incoming/UPS_Backup_2023...   574
1     edikted_112412  /share/transportation/incoming/UPS_Backup_2023...   563
2     edikted_112412  /share/transportation/incoming/UPS_Backup_2023...   561
3     edikted_112412  /share/transportation/incoming/DHL_US_2023-09-...   559
4     edikted_112412  /share/transportation/incoming/UPS_Backup_2023...   556
...              ...                                                ...   ...
1287  edikted_1sa122  C:\Users\sharon\workspace\transportation\tests...     3
1288  edikted_1sa122     C:\Users\Moshe\fixed/UPS_Backup_2023-07-16.zip     3
1289  edikted_1sa122  C:\Users\sharon\workspace\transportation\tests...     2
1290  edikted_1sa122         C:\Users\Moshe\fixed/DHL_US_2023-08-11.zip     2
1291  edikted_1sa122  C:\Users\sharon\workspace\transportation\tests...     2

[1292 rows x 3 columns]

---
## Finding #1 — Column Drift

A delimiter is lost in the source CSV. Every subsequent column receives the wrong value
(shifted right by one). The last column `additional_handling_length_girth` gets no incoming
value — the CSV exporter writes it as blank `''`, while all legitimately-absent values are
written as `'None'`. Binary signal, zero false positives.

Three distinct shift boundaries found:
- `background_image` rows 7, 22, 38, 62 — different columns lose delimiter in each row
- `edikted_212423` rows 8, 13 — `transportation` column has a datetime value (should be `None`),
  pushing `order_date` and `shopify_order_date` right by one

**Fix applied in:** `stg_shipments.sql` — `csv_sources` CTE:
```sql
where additional_handling_length_girth <> ''
```

Pandera schema now covers **all columns** dynamically — classified by name pattern into
date / numeric / categorical / drift checks. The `failure_cases` output below shows the
full multi-column impact per drifted row across all validated columns.

In [126]:
# Pandera — surfaces all symptom columns per drifted row
all_failures = []
for tbl, schema in schema_map.items():
    try:
        schema.validate(raw[tbl], lazy=True)
        print(f'  PASS  {tbl}')
    except pa.errors.SchemaErrors as exc:
        fc = exc.failure_cases.copy()
        fc['table'] = tbl
        all_failures.append(fc)
        print(f'  FAIL  {tbl}: {len(fc)} failure case(s)')

if all_failures:
    df_fail = pd.concat(all_failures, ignore_index=True)
    display(
        df_fail[['table','column','check','failure_case','index']]
        .sort_values(['table','index','column'])
        .reset_index(drop=True)
    )

  PASS  edikted_112412
  PASS  edikted_212412
  FAIL  edikted_212423: 8 failure case(s)
  FAIL  background_image: 36 failure case(s)
  PASS  edikted_1sa112
  PASS  edikted_1sa122

,table,column,check,failure_case,index
0,background_image,ID,Malformed ID,7/share/transportation/incoming/UPS_Backup_202...,6
1,background_image,additional_handling_length_girth,Blank last col — column drift,,6
2,background_image,carrier,Numeric in carrier — drift,42.44,6
3,background_image,date_received_in_hub,Unparseable date_received_in_hub,False,6
4,background_image,extra_length_surcharge,Non-numeric extra_length_surcharge,2023-08-10 14:47:00,6
5,background_image,hst_harmonized_sales_tax_duty,Non-numeric hst_harmonized_sales_tax_duty,True,6
6,background_image,insert_datetime,Unparseable insert_datetime,39820198273,6
7,background_image,invoice_date,Unparseable invoice_date,100010024892,6
8,background_image,order_date,Unparseable order_date,return,6
9,background_image,service,Numeric in service — drift,39.36,6
10,background_image,shopify_order_date,Unparseable shopify_order_date,5785562795,6
11,background_image,total_credit,Non-numeric total_credit,72380J337B4N453,6
12,background_image,warehouse_fees,Non-numeric warehouse_fees,pallet,6
13,background_image,warehouse_invoice,Non-numeric warehouse_invoice,Fedex,6
14,background_image,customs,Non-numeric customs,"\""None""",17
15,background_image,additional_handling_length_girth,Blank last col — column drift,,21
16,background_image,customs,Non-numeric customs,"NoneNone""",21
17,background_image,hst_harmonized_sales_tax_duty,Non-numeric hst_harmonized_sales_tax_duty,True,21
18,background_image,order_date,Unparseable order_date,return,21
19,background_image,shopify_order_date,Unparseable shopify_order_date,5614297366,21
20,background_image,additional_handling_length_girth,Blank last col — column drift,,37
21,background_image,date_received_in_hub,Unparseable date_received_in_hub,False,37
22,background_image,hst_harmonized_sales_tax_duty,Non-numeric hst_harmonized_sales_tax_duty,True,37
23,background_image,order_date,Unparseable order_date,dropship,37
24,background_image,service,Numeric in service — drift,50.85,37
25,background_image,shopify_order_date,Unparseable shopify_order_date,5453669491,37
26,background_image,total_credit,Non-numeric total_credit,g0L05317792C032,37
27,background_image,warehouse_fees,Non-numeric warehouse_fees,parcel,37
28,background_image,additional_handling_length_girth,Blank last col — column drift,,61
29,background_image,date_received_in_hub,Unparseable date_received_in_hub,False,61
30,background_image,hst_harmonized_sales_tax_duty,Non-numeric hst_harmonized_sales_tax_duty,True,61
31,background_image,order_date,Unparseable order_date,dropship,61
32,background_image,service,Numeric in service — drift,35.52,61
33,background_image,shopify_order_date,Unparseable shopify_order_date,6869358298,61
34,background_image,total_credit,Non-numeric total_credit,14869m0579e4J19,61
35,background_image,warehouse_fees,Non-numeric warehouse_fees,parcel,61
36,edikted_212423,additional_handling_length_girth,Blank last col — column drift,,7
37,edikted_212423,hst_harmonized_sales_tax_duty,Non-numeric hst_harmonized_sales_tax_duty,True,7
38,edikted_212423,order_date,Unparseable order_date,dropship,7
39,edikted_212423,shopify_order_date,Unparseable shopify_order_date,7659715155,7
40,edikted_212423,additional_handling_length_girth,Blank last col — column drift,,12
41,edikted_212423,hst_harmonized_sales_tax_duty,Non-numeric hst_harmonized_sales_tax_duty,True,12
42,edikted_212423,order_date,Unparseable order_date,exchange,12
43,edikted_212423,shopify_order_date,Unparseable shopify_order_date,7551116817,12

In [127]:
# Drift % per source — confirm 0.000% on clean tables
COL = 'additional_handling_length_girth'
rows, total_all = [], 0
with engine.connect() as conn:
    for tbl in CSV_TABLES:
        r = pd.read_sql(sqlalchemy.text(
            f'SELECT COUNT(*) as total, SUM(CASE WHEN "{COL}" = \'\' THEN 1 ELSE 0 END) as drifted '
            f'FROM raw."{tbl}"'
        ), conn)
        total, drifted = int(r['total'].iloc[0]), int(r['drifted'].iloc[0])
        total_all += total
        rows.append({'source': tbl, 'total_rows': total, 'drifted_rows': drifted,
                     'drift_%': f'{100*drifted/total:.3f}%'})
    total_drift = sum(r['drifted_rows'] for r in rows)
    rows.append({'source': 'ALL CSV', 'total_rows': total_all, 'drifted_rows': total_drift,
                 'drift_%': f'{100*total_drift/total_all:.3f}%'})
    display(pd.DataFrame(rows))

    print('\nDrifted row detail:')
    for tbl in CSV_TABLES:
        detail = pd.read_sql(sqlalchemy.text(
            f'SELECT "ID", carrier, service, order_date, "{COL}" as last_col '
            f'FROM raw."{tbl}" WHERE "{COL}" = \'\' '
        ), conn)
        if len(detail):
            print(f'\n{tbl}:')
            display(detail)

             source  total_rows  drifted_rows drift_%
0    edikted_112412       50000             0  0.000%
1    edikted_212412       40000             0  0.000%
2    edikted_212423       34000             2  0.006%
3  background_image       30000             4  0.013%
4           ALL CSV      154000             6  0.004%

Drifted row detail:

edikted_212423:

   ID carrier  service order_date last_col
0   8     DHL  express   dropship
1  13   Fedex      air   exchange

background_image:

,ID,carrier,service,order_date,last_col
0,7/share/transportation/incoming/UPS_Backup_202...,42.44,39.36,return,
1,22,DHL,express,return,
2,38,USPS,50.85,dropship,
3,62,DHL,35.52,dropship,

---
## Finding #2 — `join_order_id` Wrong for 100% of Rows

The source columns `join_order_id` and `join_order_name` exist in every raw table but
hold wrong values for every single row. Expected formula: `coalesce(order_id, order_name)`.

**Fix applied in:** `fact_shipments.sql`:
```sql
coalesce(order_id, order_name)                            as join_order_id_fixed,
coalesce(coalesce(order_id, order_name), '0000066600000') as join_order_name_fixed
```
Fix lives in fact, not staging — staging preserves source columns faithfully.
Original broken column kept alongside fix so lineage is explicit.

In [128]:
for tbl in TABLES:
    df = raw[tbl]
    if 'join_order_id' not in df.columns or 'order_id' not in df.columns:
        continue
    expected = df['order_id'].combine_first(df['order_name'])
    mismatch = (df['join_order_id'] != expected).sum()
    pct = round(100 * mismatch / len(df), 1)
    label = 'ALL WRONG' if pct == 100 else f'{pct}% wrong'
    print(f'{tbl}: {mismatch:,}/{len(df):,} mismatches ({label})')

edikted_112412: 50,000/50,000 mismatches (ALL WRONG)
edikted_212412: 40,000/40,000 mismatches (ALL WRONG)
edikted_212423: 34,000/34,000 mismatches (ALL WRONG)
background_image: 30,000/30,000 mismatches (ALL WRONG)
edikted_1sa112: 40,000/40,000 mismatches (ALL WRONG)
edikted_1sa122: 30,000/30,000 mismatches (ALL WRONG)

---
## Finding #3 — Dirty Column Names in `edikted_1sa112`

The JSON exporter emitted the same field multiple times with different encoding corruptions —
a `\n` prefix, a `__` prefix, and an `i` prefix — producing 3 artifact duplicates
alongside the real columns `warehouse_invoice` and `warehouse_fees`.

**Fix applied in:** `stg_shipments.sql` — `json_1sa112` CTE uses explicit
`SELECT col AS alias` for every column. Artifact columns are never selected
and cannot propagate to staging or downstream.

In [129]:
df = raw['edikted_1sa112']
artifact_cols = [c for c in df.columns if 'warehouse' in c.lower() or 'fees' in c.lower()]
print('Warehouse-related columns in edikted_1sa112 raw:')
for c in artifact_cols:
    print(f'  {repr(c)}')

print('\nSample values (first 3 rows):')
display(df[artifact_cols].head(3))

Warehouse-related columns in edikted_1sa112 raw:
  '_warehouse_invoice'
  'carriers_fees'
  '_warehouse_fees'
  '__warehouse_invoice'
  'warehouse_fees'
  '\nwarehouse_invoice'
  'warehouse_invoice'
  'iwarehouse_fees'

Sample values (first 3 rows):

,_warehouse_invoice,carriers_fees,_warehouse_fees,__warehouse_invoice,warehouse_fees,\nwarehouse_invoice,warehouse_invoice,iwarehouse_fees
0,None,76.86,None,None,None,None,100010024893,None
1,None,44.74,None,None,None,None,100010024897,None
2,None,44.05,None,None,None,None,100010024896,None

---
## Finding #4 — Column Name Variants Between Sources

Different export systems (Shopify JSON vs carrier CSV) use different field names for
the same logical columns. Key examples:

| Raw name in `edikted_1sa112` | Canonical name |
|------------------------------|----------------|
| `inserdatetime` | `insert_datetime` (typo) |
| `address` | `main_address` |

**Fix applied in:** `stg_shipments.sql` — per-source CTEs alias raw names to canonical
names before `UNION ALL`. After the union every downstream model sees a consistent schema.
Future source rename = edit one CTE only.

In [130]:
csv_cols  = set(raw['edikted_112412'].columns)
j112_cols = set(raw['edikted_1sa112'].columns)
j122_cols = set(raw['edikted_1sa122'].columns)

print('In edikted_1sa112 but not CSV (JSON-only or renamed columns):')
for c in sorted(j112_cols - csv_cols):
    print(f'  {repr(c)}')

print('\nIn CSV but not edikted_1sa112 (canonical names missing from JSON source):')
for c in sorted(csv_cols - j112_cols):
    if any(k in c for k in ['insert','warehouse','address','main']):
        print(f'  {repr(c)}')

In edikted_1sa112 but not CSV (JSON-only or renamed columns):
  '\nwarehouse_invoice'
  '__warehouse_invoice'
  '_warehouse_fees'
  '_warehouse_invoice'
  'address'
  'inserdatetime'
  'iwarehouse_fees'

In CSV but not edikted_1sa112 (canonical names missing from JSON source):
  'main_address'

---
## Finding #5 — String Null Representations Mixed Throughout

Python/pandas serialises `NaN` as `'NaN'` and `None` as `'None'` when writing CSVs.
Empty fields become `''`. Some sources also emit `'N/A'`, `'n/a'`, and dash-only placeholders
like `'----'`. All variants coexist across every source.
Standard SQL `IS NULL` matches none of them — null checks silently miss millions of values.

Two additional variants found in the `customs` column:
- `"None"` — Python serialised `None`, then a downstream tool wrapped the field in double-quotes.
  Confirmed **non-drift row** (row 17 of `background_image`, `additional_handling_length_girth = 'None'`).
  Not caught by NULLIF `'None'` — the extra quotes make it a distinct string.
- `NoneNone"` — two sentinel strings concatenated with a trailing quote, in a drift row (dropped upstream).

**Fix applied in:** `stg_shipments.sql`:
- **Text columns** — `clean_str` macro (NULLIF chain): `'None'`, `'NaN'`, `''`, `'N/A'`, `'n/a'`, `'"None"'`, dash-only regex
- **Numeric columns** — `clean_num` macro (regex allowlist): only `^-?[0-9]+(\.[0-9]+)?$` passes as `::numeric`, everything else → `NULL`. Immune to any future null variant — no enumeration needed.
- **Date columns** — `clean_date` macro (same allowlist approach for `::date` / `::timestamp`)

In [131]:
results = []
for tbl, df in raw.items():
    dash_count = sum(
        df[c].str.match(r'^-+$', na=False).sum()
        for c in df.columns
    )
    na_count = sum(
        df[c].isin(['N/A','n/a','NA','#N/A']).sum()
        for c in df.columns
    )
    results.append({
        'table':          tbl,
        "'None'":         f"{(df == 'None').sum().sum():,}",
        "'NaN'":          f"{(df == 'NaN').sum().sum():,}",
        "''":             f"{(df == '').sum().sum():,}",
        "'N/A'/'n/a'":    f"{na_count:,}",
        "'----' (dashes)":f"{dash_count:,}",
        'SQL NULL':       f"{df.isna().sum().sum():,}",
    })
display(pd.DataFrame(results))

              table     'None'   'NaN' '' 'N/A'/'n/a' '----' (dashes) SQL NULL
0    edikted_112412  2,281,923  24,552  0       4,025           1,530        0
1    edikted_212412  1,825,701  19,587  0       3,198           1,215        0
2    edikted_212423  1,551,739  16,833  2       2,792           1,044        0
3  background_image  1,369,111  14,772  4       2,441             894        0
4    edikted_1sa112  1,825,654  19,653  0       3,167           1,196  240,000
5    edikted_1sa122  1,369,169  14,765  0       2,354             849        0

In [132]:
# Per-column bad value audit — AFTER drift-row filter and null-sentinel removal.
# Mirrors exactly what staging sees before macros cast to types:
#   1. CSV drift rows dropped (additional_handling_length_girth = '' → excluded)
#   2. Known null sentinels removed (is_str_null = True → excluded)
#   3. Remaining values checked against type regex
# Anything that still fails = genuine bad value the macro must handle.

# Step 1: rebuild combined without drift rows
csv_nodrift = {
    tbl: raw[tbl][raw[tbl]['additional_handling_length_girth'] != '']
    for tbl in CSV_TABLES
}
combined_nodrift = pd.concat(
    list(csv_nodrift.values()) + [raw[tbl] for tbl in JSON_TABLES],
    ignore_index=True
)
combined_nodrift_canon = combined_nodrift[[c for c in canon_cols if c in combined_nodrift.columns]]

print(f'Rows: raw={len(combined):,}  after drift filter={len(combined_nodrift_canon):,}  dropped={len(combined)-len(combined_nodrift_canon)}')

# Step 2 & 3: remove sentinels, check type regex
rows = []
for col in canon_cols:
    kind = classify(col)
    if kind == 'drift' or col not in combined_nodrift_canon.columns:
        continue

    s       = combined_nodrift_canon[col].dropna()
    is_sent = is_str_null(s)
    s_clean = s[~is_sent]          # sentinel-removed — what staging passes to macro

    if kind == 'numeric':
        is_valid   = s_clean.str.strip().str.match(r'^-?[0-9]+(\.[0-9]+)?$', na=False)
        unexpected = s_clean[~is_valid]
        rows.append({
            'column': col, 'type': kind, 'macro': 'clean_num',
            'unexpected_bad_rows': len(unexpected),
            'unexpected_sample':   str(unexpected.unique()[:8].tolist()) if len(unexpected) else '—',
        })
    elif kind == 'date':
        is_valid   = s_clean.str.strip().str.match(r'^[0-9]{4}-[0-9]{2}-[0-9]{2}', na=False)
        unexpected = s_clean[~is_valid]
        rows.append({
            'column': col, 'type': kind, 'macro': 'clean_date',
            'unexpected_bad_rows': len(unexpected),
            'unexpected_sample':   str(unexpected.unique()[:8].tolist()) if len(unexpected) else '—',
        })
    elif kind in ('text', 'categorical'):
        rows.append({
            'column': col, 'type': kind, 'macro': 'clean_str',
            'unexpected_bad_rows': 0,
            'unexpected_sample':   '—',
        })

df_post = pd.DataFrame(rows)
bad_post = df_post[df_post['unexpected_bad_rows'] > 0].sort_values('unexpected_bad_rows', ascending=False)

print(f'\n=== Unexpected bad values after drift filter + sentinel removal ({len(bad_post)} columns) ===')
if len(bad_post):
    display(bad_post.reset_index(drop=True))
else:
    print('  None — all bad values are drift rows or known null sentinels. Macros handle everything.')

print(f'\n=== Full audit ({len(df_post)} typed columns) ===')
display(df_post.sort_values(['type', 'column']).reset_index(drop=True))

Rows: raw=224,000  after drift filter=223,994  dropped=6

=== Unexpected bad values after drift filter + sentinel removal (1 columns) ===

    column     type      macro  unexpected_bad_rows unexpected_sample
0  customs  numeric  clean_num                    1      ['\\"None"']

=== Full audit (91 typed columns) ===

,column,type,macro,unexpected_bad_rows,unexpected_sample
0,carrier,categorical,clean_str,0,—
1,service,categorical,clean_str,0,—
2,date,date,clean_date,0,—
3,date_received_in_hub,date,clean_date,0,—
4,insert_datetime,date,clean_date,0,—
...,...,...,...,...,...
86,tracking_number,text,clean_str,0,—
87,trackingnum,text,clean_str,0,—
88,transportation,text,clean_str,0,—
89,transportation_type,text,clean_str,0,—
90,values,text,clean_str,0,—

---
## Finding #6 — `ID` Absent in JSON Sources

JSON format is document-oriented — no positional row counter. CSV sources derive `ID`
from the file's row number. Before the fix, JSON rows had `NULL` as `ID` after `UNION ALL`,
breaking row-level tracing and any deduplication keyed on `ID`.

**Fix applied in:** `stg_shipments.sql` — both JSON CTEs:
```sql
row_number() over ()::text as "ID"
```
`ROW_NUMBER()` with no `ORDER BY` matches the CSV positional convention.

In [133]:
print('Raw JSON source ID columns:')
for tbl in JSON_TABLES:
    df = raw[tbl]
    if 'ID' in df.columns:
        null_count = df['ID'].isna().sum() + (df['ID'] == '').sum()
        print(f'  {tbl}: ID present — {null_count:,} null/blank (raw, before staging fix)')
    else:
        print(f'  {tbl}: no ID column in raw')

Raw JSON source ID columns:
  edikted_1sa112: no ID column in raw
  edikted_1sa122: no ID column in raw

---
## Finding #7 — Zero `total_charge` Rows

11 rows across sources have `total_charge = 0.0` with valid carrier and service.
Not a drift artifact — charge is genuinely zero.
Likely free/promotional shipments, credit adjustments, or synthetic test seeds.

**Fix:** None. Zero charge is a valid business value. Filtering would silently
remove legitimate records. Monitor count over time for unexpected spikes.

In [134]:
with engine.connect() as conn:
    found = False
    for tbl in TABLES:
        r = pd.read_sql(sqlalchemy.text(
            f'SELECT carrier, service, total_charge FROM raw."{tbl}" '
            f"WHERE total_charge ~ '^-?[0-9]+(\\\\.[0-9]+)?$' AND total_charge::numeric = 0"
        ), conn)
        if len(r):
            found = True
            print(f'{tbl}: {len(r)} zero-charge row(s)')
            display(r)
    if not found:
        print('No zero-charge rows found.')

No zero-charge rows found.

---
## Finding #8 — Same `order_id` Across Multiple Source Files

10 `order_id` values appear in more than one source file. Each source covers a different
carrier export — the same order can have shipments via multiple carriers.

**Distinguishing test:** distinct `tracking_number` per appearance = separate shipments (expected).
Same `tracking_number` across sources = duplicate record (not expected).

**Fix:** None — all 10 orders have distinct tracking numbers, confirming separate shipments.
Mart models needing deduplication should use `(order_id, tracking_number)` as composite key.

In [135]:
sql = (
    'SELECT order_id, COUNT(*) as appearances, '
    'COUNT(DISTINCT tracking_number) as distinct_tracking, '
    "STRING_AGG(DISTINCT tbl, ', ' ORDER BY tbl) as in_tables "
    'FROM ('
    "  SELECT order_id, tracking_number, 'edikted_112412' as tbl FROM raw.\"edikted_112412\" UNION ALL"
    "  SELECT order_id, tracking_number, 'edikted_212412'         FROM raw.\"edikted_212412\" UNION ALL"
    "  SELECT order_id, tracking_number, 'edikted_212423'         FROM raw.\"edikted_212423\" UNION ALL"
    "  SELECT order_id, tracking_number, 'edikted_1sa112'         FROM raw.\"edikted_1sa112\" UNION ALL"
    "  SELECT order_id, tracking_number, 'edikted_1sa122'         FROM raw.\"edikted_1sa122\""
    ') x GROUP BY order_id HAVING COUNT(*) > 1 ORDER BY appearances DESC LIMIT 10'
)
with engine.connect() as conn:
    r = pd.read_sql(sqlalchemy.text(sql), conn)
    print(f'order_ids in multiple sources: {len(r)}')
    display(r)

order_ids in multiple sources: 10

,order_id,appearances,distinct_tracking,in_tables
0,565641,6,6,"edikted_112412, edikted_1sa112, edikted_212423"
1,669499,6,6,"edikted_112412, edikted_1sa112, edikted_1sa122..."
2,899828,6,6,"edikted_112412, edikted_1sa112, edikted_1sa122..."
3,442394,5,5,"edikted_112412, edikted_212412"
4,378537,5,5,"edikted_112412, edikted_1sa112, edikted_1sa122..."
5,392742,5,5,"edikted_112412, edikted_1sa112, edikted_1sa122"
6,268825,5,5,"edikted_112412, edikted_1sa122, edikted_212412..."
7,114496,5,5,"edikted_112412, edikted_1sa112, edikted_1sa122..."
8,119432,5,5,"edikted_112412, edikted_1sa112, edikted_1sa122..."
9,179292,5,5,"edikted_112412, edikted_1sa112, edikted_1sa122..."

---
## Findings #9-10 — Synthetic Data Caps

Value distributions were capped during data generation:
- `total_charge` max = $100 (real express air can exceed $500)
- `weight_lbs` max = 20 lbs (real freight often > 100 lbs)
- Tracking numbers are 8-char alphanumeric — real UPS = 18-char `1Z...`, FedEx = 12-digit, USPS = 22-digit

**Fix:** None — document only. Do not build pricing models, SLA thresholds, or
carrier-routing logic against these values.

In [136]:
for col, label in [('total_charge', 'total_charge ($)'), ('weight_lbs', 'weight_lbs')]:
    all_vals = []
    for df in raw.values():
        if col in df.columns:
            parsed = pd.to_numeric(df[col], errors='coerce').dropna()
            all_vals.append(parsed)
    combined = pd.concat(all_vals)
    print(f'{label}: min={combined.min():.2f}  max={combined.max():.2f}  '
          f'mean={combined.mean():.2f}  p95={combined.quantile(0.95):.2f}')

print('\nTracking number format sample:')
for tbl in ['edikted_112412', 'edikted_1sa112']:
    samples = raw[tbl]['tracking_number'].dropna().head(3).tolist()
    print(f'  {tbl}: {samples}')

total_charge ($): min=0.00  max=100.00  mean=49.99  p95=95.01
weight_lbs: min=0.00  max=20.00  mean=10.00  p95=19.00

Tracking number format sample:
  edikted_112412: ['421483Zm96296E2', '04gg7b156778745', '67cd982V7245992']
  edikted_1sa112: ['58fF16484L65609', 'X26737Dy6719053', '3i7z7x849316529']

---
## Summary — Findings Overview

**Where fixed** — dbt layer where the fix will be applied:
- **Staging** (`stg_shipments.sql`) — structural fixes applied once; every downstream model inherits automatically.
- **Fact** (`fact_shipments.sql`) — derived business logic and recalculated join keys.

In [137]:
from IPython.display import HTML
import pandas as pd

findings = [
    {'#': 1, 'Severity': 'ERROR',
     'Finding': 'Column drift — 6 corrupted rows across 3 shift boundaries',
     'Problem': 'Missing CSV delimiter shifts all columns right. carrier/service/charge/date get garbage values. Downstream aggregations wrong; joins on order_id may fail if ID column corrupted.',
     'dbt Fix Location': 'Staging — csv_sources CTE',
     'Fix Applied': 'WHERE additional_handling_length_girth <> \'\'',
     'Fix Rationale': '6 rows out of 224,000 = 0.003% — safe to drop. No recovery possible: shift boundary differs per row, back-shifting requires per-row logic with no ground truth.',
     'Status': '🔧 dbt staging'},
    {'#': 2, 'Severity': 'ERROR',
     'Finding': 'join_order_id / join_order_name wrong for 100% of rows',
     'Problem': 'Any downstream join on join_order_id to link shipments to orders produces 0 matches. Entire order-to-shipment relationship broken.',
     'dbt Fix Location': 'Fact — new columns alongside originals',
     'Fix Applied': 'join_order_id_fixed = coalesce(order_id, order_name)\njoin_order_name_fixed = coalesce(coalesce(order_id, order_name), \'0000066600000\')',
     'Fix Rationale': '100% of 224,000 rows affected — cannot drop, must fix. Added as new columns so broken originals remain visible and existing downstream queries do not silently change behavior.',
     'Status': '🔧 dbt fact'},
    {'#': 3, 'Severity': 'ERROR',
     'Finding': 'Dirty column names in edikted_1sa112 — 3 artifact duplicates of warehouse_invoice / warehouse_fees',
     'Problem': 'SELECT * pulls in 3 corrupted copies of the same field, causing duplicate data in aggregations and schema conflicts after UNION ALL.',
     'dbt Fix Location': 'Staging — json_1sa112 CTE',
     'Fix Applied': 'Explicit SELECT listing all 92 canonical columns by name; artifact columns (_warehouse_invoice, __warehouse_invoice, iwarehouse_fees) excluded',
     'Fix Rationale': 'Artifacts carry real values in ~2% of rows — including them inflates counts and sums. Explicit SELECT is zero data loss. DROP COLUMN not available in CTE context.',
     'Status': '🔧 dbt staging'},
    {'#': 4, 'Severity': 'WARN',
     'Finding': 'Column name variants between JSON and CSV sources (e.g. inserdatetime vs insert_datetime)',
     'Problem': 'UNION ALL requires identical column names. Mismatches cause query errors or silently produce NULL in the canonical column for all JSON rows.',
     'dbt Fix Location': 'Staging — per-source CTEs',
     'Fix Applied': 'inserdatetime AS insert_datetime\n_warehouse_invoice AS warehouse_invoice\naddress AS main_address\n_warehouse_fees AS warehouse_fees',
     'Fix Rationale': '2 renamed columns affect 70,000 JSON rows (31% of total). Aliasing in CTEs costs nothing; one edit per source if upstream names change. Fixing at ingest would require re-loading raw data.',
     'Status': '🔧 dbt staging'},
    {'#': 5, 'Severity': 'WARN',
     'Finding': "String nulls mixed: 'None', 'NaN', '', 'N/A', '----', '\"None\"', 'NoneNone' across all sources",
     'Problem': (
         "SQL IS NULL misses all string variants. Filters like WHERE total_charge IS NOT NULL pass through "
         "'None' strings and corrupt aggregations. Quoted variant '\"None\"' and concatenated 'NoneNone' "
         "found in customs column — not caught by NULLIF exact-match blocklist.\n\n"
         "Per-column audit (cell below) found 11 columns with unexpected bad values (non-sentinel, "
         "failing type regex). All ≤6 rows each → all from the 6 drift rows, already dropped upstream. "
         "Only exception: customs (2 non-drift rows: '\"None\"', 'NoneNone\"') — not sentinels, not drift."
     ),
     'dbt Fix Location': 'Staging — 3 macros, all 92 columns',
     'Fix Applied': (
         'Three macros, one per column type:\n\n'
         '① clean_str (text cols) — NULLIF blocklist:\n'
         "  NULLIF(NULLIF(NULLIF(col,'None'),'NaN'),'')\n"
         "  + dash-only regex (e.g. '----' → NULL)\n"
         "  Blocklist safe for text: avoids false positives\n"
         "  on names containing 'none', 'nan' as substrings.\n\n"
         '② clean_num (numeric cols) — regex allowlist:\n'
         "  CASE WHEN TRIM(col) ~ '^-?[0-9]+(\\.[0-9]+)?$'\n"
         '  THEN TRIM(col)::numeric END\n'
         '  Only valid numbers pass. All else → NULL.\n'
         "  Immune to '\"None\"', 'NoneNone', future variants.\n"
         '  No enumeration needed.\n\n'
         '③ clean_date (date cols) — same allowlist pattern:\n'
         "  CASE WHEN TRIM(col) ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'\n"
         '  THEN TRIM(col)::date/timestamp END\n\n'
         'Validation — raw vs staging null comparison:\n'
         '  Max gap per column = -6 (= drift rows dropped).\n'
         '  No column shows larger gap → macros did not\n'
         '  over-null any valid values.'
     ),
     'Fix Rationale': (
         '~9M string-null cells across 224,000 rows.\n\n'
         'Why allowlist for numeric/date (not blocklist):\n'
         'NULLIF enumeration would miss "None" (double-quoted)\n'
         'and NoneNone (concatenated) — new variants not in list.\n'
         'Regex allowlist passes only conforming values; anything\n'
         'else → NULL without needing to know its exact form.\n\n'
         'Why blocklist for text:\n'
         "LOWER(col) LIKE '%none%' risks false positives on\n"
         'customer names, addresses, free-text fields. NULLIF\n'
         'on exact sentinel strings is safe — text columns have\n'
         'no "wrong type" to catch with regex.\n\n'
         'Each macro defined once in dbt/macros/, applied to\n'
         'all 92 columns in the final SELECT of stg_shipments.sql.'
     ),
     'Status': '🔧 dbt staging'},
    {'#': 6, 'Severity': 'WARN',
     'Finding': 'ID absent in JSON sources — all rows were NULL',
     'Problem': 'Row-level tracing and deduplication keyed on ID silently fail for all JSON rows.',
     'dbt Fix Location': 'Staging — json_1sa112 and json_1sa122 CTEs',
     'Fix Applied': 'ROW_NUMBER() OVER ()::text AS "ID"',
     'Fix Rationale': '70,000 JSON rows (31% of total) had no ID. ROW_NUMBER() matches the positional convention used by CSV sources. Not globally unique across sources — by design, same as CSV.',
     'Status': '🔧 dbt staging'},
    {'#': 7, 'Severity': 'WARN',
     'Finding': 'Zero total_charge — 11 rows with valid carrier/service',
     'Problem': 'Zero charge rows suppress revenue averages if included; hide free-shipment SLA events if excluded.',
     'dbt Fix Location': '— no fix needed',
     'Fix Applied': '—',
     'Fix Rationale': '11 rows out of 224,000 = 0.005%. Carrier and service are valid — not drift artifacts. Dropping distorts carrier cost analysis. Monitor: unexpected growth signals a billing feed issue.',
     'Status': '👀 Monitor'},
    {'#': 8, 'Severity': 'WARN',
     'Finding': 'Same order_id across multiple source files — 10 orders, distinct tracking numbers',
     'Problem': 'Dedup on order_id alone drops valid multi-carrier shipments. Affects unique shipment counts and per-order total cost in mart models.',
     'dbt Fix Location': '— no fix needed',
     'Fix Applied': '—',
     'Fix Rationale': '10 order_ids = 0.004% of unique orders. All 10 have distinct tracking numbers — confirmed separate shipments. Correct dedup grain for mart models: (order_id, tracking_number).',
     'Status': '👀 Monitor'},
    {'#': 9, 'Severity': 'INFO',
     'Finding': 'total_charge capped at $100, weight_lbs capped at 20 lbs',
     'Problem': 'Pricing models or anomaly detectors trained on this data will be systematically wrong on real shipments.',
     'dbt Fix Location': '— synthetic data',
     'Fix Applied': 'Documented in schema.yml column descriptions',
     'Fix Rationale': 'EDA hard cap: max total_charge = $100.00, max weight_lbs = 20.00, perfectly uniform distributions. Data generation artifact — no transformation recovers real values.',
     'Status': '📝 Document only'},
    {'#': 10, 'Severity': 'INFO',
     'Finding': 'Tracking numbers are 8-char alphanumeric — not real carrier format',
     'Problem': 'Carrier lookup APIs that validate format will reject all rows. Real UPS = 18-char 1Z..., FedEx = 12-digit, USPS = 22-digit.',
     'dbt Fix Location': '— synthetic data',
     'Fix Applied': 'Documented in schema.yml column descriptions',
     'Fix Rationale': '100% of tracking numbers are 8-char synthetic strings. No format validation can be added — it would reject all rows.',
     'Status': '📝 Document only'},
]

df = pd.DataFrame(findings)

severity_colors = {'ERROR': '#ffd6d6', 'WARN': '#fff3cd', 'INFO': '#d6eaff'}

def style_row(row):
    color = severity_colors.get(row['Severity'], 'white')
    return [f'background-color:{color}'] * len(row)

styled = (
    df.style
    .apply(style_row, axis=1)
    .set_properties(**{'white-space': 'pre-wrap', 'text-align': 'left',
                       'vertical-align': 'top', 'font-size': '12px',
                       'max-width': '280px'})
    .set_table_styles([{'selector': 'th',
                        'props': [('background-color','#2c2c2c'),('color','white'),
                                  ('font-size','12px'),('text-align','left'),
                                  ('position','sticky'),('top','0'),('z-index','1')]}])
    .hide(axis='index')
)

html = styled.to_html()
display(HTML(f'<div style="height:450px;overflow-y:auto;border:1px solid #ddd;">{html}</div>'))